[analytic.metadata]
categories = ["detect"]
confidence = "high"
contributors = ["Daniel Stepanic"]
created_date = "12/04/2019"
description = "Identifies an executable file written by a Microsoft Office application that is then later run as it's own process. This behavior is indicative of suspicious activity that can be malicious macros or technologies such as Dynamic Data Exchange (DDE)."
id = "3d307e78-b336-450c-8149-3651fad179e8"
name = "Executable Written and Executed by Microsoft Office Applications"
os = ["windows"]
tactics = ["Execution"]
techniques = ["T1173"]
updated_date = "12/04/2019"
references = []

[analytic]
query = '''
sequence with maxspan=5m
  [file where file_name == "*.exe" and process_name in ("winword.exe", "excel.exe", "powerpnt.exe")] by file_path
  [process where true] by process_path
'''
