[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Daniel Stepanic"]
created_date = "12/04/2019"
description = "Identifies initial system enumeration and discovery commands tied to Koadic's process ancestry."
id = "35d27938-d13d-4bcd-9be7-3a69d208c63f"
name = "Discovery and Enumeration of System Information via Koadic"
os = ["windows"]
tactics = ["Discovery"]
tags = ["koadic"]
techniques = ["T1087","T1096","T1033"]
updated_date = "12/04/2019"
references = []

[analytic]
query = '''
sequence by user_name with maxspan=10m
 [process where subtype.create and child of [process where parent_process_name == "rundll32.exe"]
     and process_name in ("hostname.exe", "ipconfig.exe", "net.exe", "net1.exe", "tasklist.exe", "whoami.exe") and
     descendant of [process where parent_process_name == "wmiprvse.exe"]]
 [process where subtype.create and child of [process where parent_process_name == "rundll32.exe"]
     and process_name in ("hostname.exe", "ipconfig.exe", "net.exe", "net1.exe", "tasklist.exe", "whoami.exe") and
     descendant of [process where parent_process_name == "wmiprvse.exe"]]
| unique user_name
'''
