[analytic.metadata]
categories = ["detect"]
confidence = "medium"
contributors = ["Daniel Stepanic"]
created_date = "12/04/2019"
description = "Identifies command execution via WMI with redirected output. WMI provides a method to execute a process on a local or remote host, but does not expose a way to read any console output. To get around this restriction, some administrators or attackers will execute ``cmd.exe`` with output redirection to a file. Then the file can be retrieved to read program output."
id = "7c7f3114-7bdd-4477-a4e0-b5105b6babd8"
name = "WMI Execution with Command Line Redirection"
os = ["windows"]
tactics = ["Collection"]
tags = ["koadic"]
techniques = ["T1074"]
updated_date = "12/04/2019"
references = ["https://www.elastic.co/blog/embracing-offensive-tooling-building-detections-against-koadic-using-eql"]

[analytic]
query = '''
sequence with maxspan=5s by unique_pid
  [process where subtype.create and process_name == "cmd.exe" and command_line == "*>*" and
    descendant of [process where process_name == "wmiprvse.exe"]]
  [file where subtype.create and wildcard(file_name, "*.txt", "*.log")]
'''
